server:
  port: 8088

spring:
  profiles:
    group:
      "local" : "local, common"
      "dev" : "dev, common"
      "real" : "real, common"
    active: dev   #활성 프로필 설정(local, dev, real)

--- # local 설정
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/howtaxing?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: Xmonster11@@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: -1
      initial-size: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: 'select 1'
      time-between-eviction-runs-millis: 3000
  batch:
    initialize-schema: always
  mvc:
    custom-uri-logging-filter:
      enabled: true
      level: info
    static-path-pattern: "/static/**"
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:log4jdbc:mysql://devapp.how-taxing.com:3306/howtaxing?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: Xmonster11@@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: -1
      initial-size: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: 'select 1'
      time-between-eviction-runs-millis: 3000
  batch:
    initialize-schema: always
  mvc:
    custom-uri-logging-filter:
      enabled: true
      level: info
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false

--- # real 설정
spring:
  config:
    activate:
      on-profile: "real"
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/howtaxing?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: Xmonster11@@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: -1
      initial-size: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: 'select 1'
      time-between-eviction-runs-millis: 3000
  batch:
    initialize-schema: always
  mvc:
    custom-uri-logging-filter:
      enabled: true
      level: info
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false